import { useState } from 'react';
import { Upload, ShieldCheck, Play, Loader2, PlugZap } from 'lucide-react';
import { parseTelopText, LineData, applyDeterministicRules } from './utils/textProcessor';
import { checkTeopWithGemini, listAvailableModels } from './services/gemini';
import { DiffViewer } from './components/DiffViewer';

function App() {
    const [lines, setLines] = useState<LineData[]>([]);
    const [apiKey, setApiKey] = useState(localStorage.getItem('gemini_api_key') || '');

    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState('');
    const [debugLog, setDebugLog] = useState('');

    const handleFileUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
        const file = event.target.files?.[0];
        if (!file) return;

        const reader = new FileReader();
        reader.onload = (e) => {
            const text = e.target?.result as string;
            const parsed = parseTelopText(text);
            setLines(parsed);

        };
        reader.readAsText(file);
    };

    const saveApiKey = (key: string) => {
        setApiKey(key);
        localStorage.setItem('gemini_api_key', key);
    };

    const testConnection = async () => {
        if (!apiKey) {
            alert("API Keyを入力してください");
            return;
        }
        setDebugLog("Testing connection...");
        try {
            const models = await listAvailableModels(apiKey);
            const names = models.map((m: any) => m.name.replace('models/', ''));
            setDebugLog(`✅ Connection Success!\nAvailable Models:\n${names.join('\n')}`);
        } catch (err: any) {
            setDebugLog(`❌ Connection Failed:\n${err.message}`);
        }
    };

    const runAICheck = async () => {
        if (!apiKey) {
            alert("API Keyを設定してください");
            return;
        }
        setIsLoading(true);
        setError('');
        setDebugLog('Running AI Check...');

        try {
            const corrections = await checkTeopWithGemini(apiKey, lines);

            // Update lines with corrections
            const updatedLines = lines.map(line => {
                const fix = corrections.find((c: any) => c.id === line.id);

                if (fix) {
                    let correctedText = fix.corrected;
                    let reasons = [fix.reason];
                    let level = fix.level || "Warning"; // Default to Warning if undefined

                    // Post-process: Ensure Code Rules are applied to AI output too
                    const codeCheck = applyDeterministicRules(correctedText);
                    if (codeCheck) {
                        correctedText = codeCheck.text;
                        reasons.push(codeCheck.reason || "");
                        level = "Critical"; // Code rules are critical
                    }

                    return {
                        ...line,
                        correction: correctedText,
                        reason: reasons.join(' + '),
                        level: level
                    };
                }
                return line;
            });

            setLines(updatedLines);
            setDebugLog('✅ AI Check Complete');
        } catch (err: any) {
            const msg = "エラーが発生しました: " + (err.message || String(err));
            setError(msg);
            setDebugLog(`❌ Error:\n${msg}`);
        } finally {
            setIsLoading(false);
        }
    };

    // Generate Chatwork Report
    const copyReport = () => {
        const totalLines = lines.length;
        const validLines = lines.filter(l => !l.isNoise).length;
        const issues = lines.filter(l => l.correction);

        const details = issues.map(line => {
            const levelIcon = line.level === "Critical" ? "⛔" : line.level === "Warning" ? "⚠️" : "ℹ️";
            return `--------------------------------------------------
${levelIcon} [${line.level || "Warning"}] ${line.timestamp || "(No Time)"}
原文: ${line.originalText}
修正: ${line.correction}
理由: ${line.reason}`;
        }).join('\n');

        const report = `[info][title]TelopGuard 校正レポート[/title]✅ AI校正チェック完了

■ 検査統計
・総行数: ${totalLines}行
・検査対象: ${validLines}行
・AI指摘数: ${issues.length}件

■ 詳細レポート
${details}

※このレポートはAIによる自動チェック結果です。
誤検知（過剰な指摘）が含まれる可能性があるため、
最終的な採用・不採用は編集者の目視判断で行っています。
(Generated by TelopGuard v2.4)[/info]`;

        navigator.clipboard.writeText(report);
        alert("Chatwork用レポートをコピーしました！");
    };

    return (

        <div className="min-h-screen bg-[#0f172a] text-slate-200 font-sans flex flex-col">
            {/* Header */}
            <header className="flex justify-between items-center px-6 py-4 bg-[#1e293b] border-b border-slate-700 shadow-md">
                <h1 className="text-xl font-bold flex items-center gap-2 text-indigo-400">
                    <ShieldCheck className="w-6 h-6" />
                    TelopGuard <span className="text-xs bg-indigo-900 text-indigo-300 px-2 py-0.5 rounded-full">v2.4</span>
                </h1>
                <div className="flex gap-4 items-center">
                    <div className="flex items-center gap-2 bg-slate-800 px-3 py-1.5 rounded border border-slate-600">
                        <span className="text-xs text-slate-400 font-medium">API KEY:</span>
                        <input
                            type="password"
                            placeholder="Gemini API Key"
                            className="bg-transparent border-none text-sm w-32 focus:outline-none text-slate-200 placeholder-slate-600"
                            value={apiKey}
                            onChange={(e) => saveApiKey(e.target.value)}
                        />
                    </div>
                    <button onClick={testConnection} className="text-xs bg-slate-700 hover:bg-slate-600 px-3 py-1.5 rounded transition-colors text-slate-300 flex items-center gap-1">
                        <PlugZap size={14} /> Test
                    </button>
                </div>
            </header>

            {/* Main Content - Split View */}
            <main className="flex-1 flex overflow-hidden">
                {/* Left Panel: Source / Input */}
                <div className="w-1/2 flex flex-col border-r border-slate-700 bg-[#0f172a]">
                    <div className="p-3 border-b border-slate-700 bg-[#1e293b] flex justify-between items-center">
                        <h2 className="text-sm font-bold flex items-center gap-2 text-slate-300">
                            <Upload size={16} /> Subtitle Source
                        </h2>
                        {lines.length > 0 && (
                            <button onClick={() => { setLines([]); }} className="text-xs text-slate-500 hover:text-slate-300">
                                Clear
                            </button>
                        )}
                    </div>

                    <div className="flex-1 overflow-y-auto p-4 relative">
                        {/* Drag & Drop Overlay or File List */}
                        {lines.length === 0 ? (
                            <div className="h-full border-2 border-dashed border-slate-700 rounded-xl flex flex-col items-center justify-center text-slate-500 hover:border-indigo-500 hover:bg-slate-800 transition-all cursor-pointer relative">
                                <input
                                    type="file"
                                    accept=".txt"
                                    onChange={handleFileUpload}
                                    className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
                                />
                                <Upload size={48} className="mb-4 text-indigo-500" />
                                <p className="font-bold text-lg text-slate-400">Drag & Drop Text File</p>
                                <p className="text-xs mt-2">.txt (Premiere Pro / Vrew)</p>
                            </div>
                        ) : (
                            <div className="space-y-1 font-mono text-sm leading-relaxed text-slate-400">
                                {lines.map(line => (
                                    <div key={line.id} className={`p-2 rounded ${line.isNoise ? 'opacity-30' : 'hover:bg-slate-800'}`}>
                                        <div className="text-xs text-slate-600 mb-0.5">{line.timestamp}</div>
                                        <div>{line.originalText}</div>
                                    </div>
                                ))}
                            </div>
                        )}
                    </div>
                </div>

                {/* Right Panel: Result */}
                <div className="w-1/2 flex flex-col bg-[#0f172a]">
                    <div className="p-3 border-b border-slate-700 bg-[#1e293b] flex justify-between items-center">
                        <h2 className="text-sm font-bold flex items-center gap-2 text-slate-300">
                            <ShieldCheck size={16} className="text-green-500" /> Analysis Result
                        </h2>
                        <div className="flex gap-2">
                            {/* Report Copy Button */}
                            {lines.length > 0 && (
                                <button
                                    onClick={copyReport}
                                    className="text-xs bg-slate-700 hover:bg-slate-600 text-slate-200 px-3 py-1.5 rounded border border-slate-600 transition-colors flex items-center gap-1"
                                    title="Copy Summary Report for Chatwork"
                                >
                                    📑 Copy Report
                                </button>
                            )}
                            <button
                                onClick={runAICheck}
                                disabled={isLoading || lines.length === 0}
                                className="bg-indigo-600 hover:bg-indigo-500 text-white px-4 py-1.5 rounded text-sm font-bold shadow disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
                            >
                                {isLoading ? <Loader2 className="animate-spin" size={14} /> : <Play fill="currentColor" size={14} />}
                                {isLoading ? 'Checking...' : 'Run AI Check'}
                            </button>
                        </div>
                    </div>

                    <div className="flex-1 overflow-y-auto p-4 bg-[#020617] text-slate-300 font-mono text-sm">
                        {error && (
                            <div className="bg-red-900/50 text-red-200 p-4 rounded mb-4 border border-red-800 text-sm">
                                ❌ {error}
                            </div>
                        )}

                        {debugLog && !lines.length && (
                            <div className="text-xs text-slate-600 whitespace-pre-wrap font-mono">{debugLog}</div>
                        )}

                        <DiffViewer lines={lines} />
                    </div>
                </div>
            </main>
        </div>
    )
}

export default App
